### ISSUE TITLE
Seeds file parser broken?

### ISSUE THREAD

**Issue by earthquakesan** [AKSW/Squirrel#17]
```
java.net.UnknownHostException: anbri.org/75.101.157.128: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at org.aksw.simba.squirrel.queue.RDBQueue$1.next(RDBQueue.java:104)
	at org.aksw.simba.squirrel.queue.RDBQueue$1.next(RDBQueue.java:94)
	at org.aksw.simba.squirrel.queue.AbstractIpAddressBasedQueue.getNextUris(AbstractIpAddressBasedQueue.java:61)
	at org.aksw.simba.squirrel.frontier.impl.FrontierImpl.getNextUris(FrontierImpl.java:93)
	at org.aksw.simba.squirrel.components.FrontierComponent.handleData(FrontierComponent.java:121)
	at org.aksw.simba.squirrel.rabbit.RPCServer$MsgProcessingTask.run(RPCServer.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.net.UnknownHostException: anbri.org/75.101.157.128
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at org.aksw.simba.squirrel.queue.RDBQueue$1.next(RDBQueue.java:104)
	at org.aksw.simba.squirrel.queue.RDBQueue$1.next(RDBQueue.java:94)
	at org.aksw.simba.squirrel.queue.AbstractIpAddressBasedQueue.getNextUris(AbstractIpAddressBasedQueue.java:61)
	at org.aksw.simba.squirrel.frontier.impl.FrontierImpl.getNextUris(FrontierImpl.java:93)
	at org.aksw.simba.squirrel.components.FrontierComponent.handleData(FrontierComponent.java:121)
	at org.aksw.simba.squirrel.rabbit.RPCServer$MsgProcessingTask.run(RPCServer.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.net.UnknownHostException: anbri.org/75.101.157.128
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at org.aksw.simba.squirrel.queue.RDBQueue$1.next(RDBQueue.java:104)
	at org.aksw.simba.squirrel.queue.RDBQueue$1.next(RDBQueue.java:94)
	at org.aksw.simba.squirrel.queue.AbstractIpAddressBasedQueue.getNextUris(AbstractIpAddressBasedQueue.java:61)
	at org.aksw.simba.squirrel.frontier.impl.FrontierImpl.getNextUris(FrontierImpl.java:93)
	at org.aksw.simba.squirrel.components.FrontierComponent.handleData(FrontierComponent.java:121)
	at org.aksw.simba.squirrel.rabbit.RPCServer$MsgProcessingTask.run(RPCServer.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by MichaelRoeder** [comment]
The frontier is aksed for the next URI by one of the workers. It tries to get the next URI from the queue, but while creating the `InetAddress` object, the method `InetAddress.getByName` throws the exception shown above.
https://github.com/AKSW/Squirrel/blob/master/src/main/java/org/aksw/simba/squirrel/queue/RDBQueue.java#L104

The problem is that this method tries to get the IP of a given host name. However, this should not be done in this step, but before. I would strongly suggest to replace this by parsing the bytes of the IP and using the `InetAddress.getByAddress` method.

**Comment by MichaelRoeder** [comment]
The queue now uses only the IP String instead of the `hostname/IP` String that can be seen in the exceptions above. That should prevent it from trying to determine the IP address again, because the `InetAddress.getByName` should simpy parse the given IP.

However, it needs to be checked by a JUnit test.
